### PR TITLE
feat(lint): add constant-case rule

### LINKED ISSUE #6: rule: enforce CONSTANT_CASE environment variable names
### Problem

Environment variable names containing lowercase characters are inconsistent with the conventional CONSTANT_CASE naming style and make dotenv files harder to scan and maintain consistently.

The rule should report and warn about otherwise valid environment variable keys that contain lowercase letters.

### Proposed rule name

constant-case

### Bad example

```env
database_url=postgresql://localhost/app
Database_URL=postgresql://localhost/app
apiToken=example
```

### Good example

```env
DATABASE_URL=postgresql://localhost/app
API_TOKEN=example
API_V2_URL=https://example.test
```

### Expected output

[warn] constant-case .env:1 database_url should use CONSTANT_CASE: DATABASE_URL

### Evidence level

Deterministic (for exact findings proven from local files, schemas, configuration, Git state or other directly inspectable local evidence.)

### Notes

The rule should inspect parsed environment variable keys and report keys containing lowercase ASCII letters.

Structural naming problems such as hyphens, dots, spaces, or keys beginning with a number should remain the responsibility of invalid-key-name.

Autofix should not be implemented initially. Renaming a variable may break references in source code, CI configuration, deployment configuration, Docker files, and documentation.

Expected valid characters are uppercase ASCII letters, digits, and underscores, subject to the existing invalid-key-name rule.

### PR DESCRIPTION
**Pull request by Nitjsefnie**
Fixes #6.

New warn-severity deterministic rule `constant-case`: reports otherwise-valid keys containing lowercase ASCII letters as `<key> should use CONSTANT_CASE: <UPPER>` (uppercasing ASCII a–z only for the suggestion). **No autofix**, per the issue — renames break external references.

**Division with `invalid-key-name`** follows the codebase convention of exclusive lanes (the way `duplicate-key` skips `incorrect-delimiter`'s lines): the rule reuses the shared `validKeyName` guard, so hyphens/dots/spaces/leading digits stay `invalid-key-name`'s business — `api-key` yields only the invalid-key-name error. A test documents the division.

Scaffolding matches existing rules everywhere they appear (impl, tests in the `runRuleTest` style, `rules.All()` registry, `compat.go` constructor, `docs/lint/rules/deterministic/constant-case.md` page, Rule Catalog row); CLI completions pick the name up automatically from the registry. Six tests cover the issue's bad/good examples verbatim plus the division case.

One deliberate divergence: the issue's sample shows a `[warn]` badge, but vaar's reporter renders `warn constant-case file:line message` — the message body matches the issue verbatim and the line format follows the existing reporter (no reporter changes).

Coordination note: #30 (open) adds `Description()` to the `Rule` interface — whichever PR lands second needs a one-line addition on the other's shape; happy to rebase either way.

Gates: `make lint`/`vet`/`build` clean; `make test` green except the two known root-environment chmod-0 tests (fail on clean main too, invisible to CI). Rule behavior verified live against a demo dotenv with the built binary.

## AI assistance disclosure

Implemented with AI assistance (Kimi K3, briefed and verified by Claude); gates, tests, and live rule output were independently re-verified before opening.

## Summary by CodeRabbit

- **New Features**
  - Added the deterministic `constant-case` lint rule to the built-in rule set.
  - Emits warnings when portable env-key casing includes lowercase ASCII letters and suggests the `CONSTANT_CASE` equivalent (manual rename).

- **Documentation**
  - Added a `constant-case` rule page and updated the rule catalog, including its `Deterministic` evidence level and examples.

- **Tests**
  - Added test coverage for lowercase, mixed-case, and camelCase warnings, while allowing already-constant uppercase keys and digit+underscore keys.
  - Verified structurally invalid keys are handled by the existing `invalid-key-name` rule.

### CODE REVIEW

File: internal/lint/rules/deterministic/constant_case.go [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+				fmt.Sprintf("%s should use CONSTANT_CASE: %s", line.Key, upper),
+			))
+		}
+	}
+	return findings, nil
+}
+
+// constantCaseKey uppercases ASCII lowercase letters and leaves every other
+// byte untouched.
+func constantCaseKey(key string) string {
```
[the remark this answers is not in the document]
Comment (Nitjsefnie) [reply internal/lint/rules/deterministic/constant_case.go:54]: Right — this was reworded on the current head (467f44a): the doc comment now reads "uppercases ASCII lowercase letters and leaves every other rune untouched", matching the `strings.Map` rune semantics.

[the remark this answers is not in the document]
Comment (TFM-HITESH) [reply internal/lint/rules/deterministic/constant_case.go:54]: Will check your latest commit @Nitjsefnie

File: internal/lint/rules/deterministic/constant_case_test.go [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+
+// Structurally invalid keys are reported by invalid-key-name, not by
+// constant-case: each rule stays in its own lane.
+func TestConstantCaseLeavesInvalidKeysToInvalidKeyName(t *testing.T) {
+	runRuleTest(t, ruleTestCase{
+		rule:      deterministic.NewConstantCase(),
+		input:     []byte("api-key=value\n1api=value\n"),
+		wantCount: 0,
+	})
+}
```
[the remark this answers is not in the document]
Comment (Nitjsefnie) [reply internal/lint/rules/deterministic/constant_case_test.go:89]: Good catch — asserting only that constant-case is silent would pass just as well if *nothing* flagged those keys, which is the opposite of pinning a boundary. Fixed in b254a0a: the test now also asserts `invalid-key-name` reports both `api-key` and `1api`.

Verified it bites rather than just passing: with `invalidKeyNameRule.Run` stubbed to return no findings, the test fails (`unexpected finding count: got 0 want 2`); restored, it passes.

File: docs/lint/rules/deterministic/constant-case.md [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+
+# constant-case
+
+Warns about portable keys that are not CONSTANT_CASE.
+
+## What it catches
+
+Keys that match the portable env-key pattern but contain lowercase ASCII
+letters. The message suggests the CONSTANT_CASE form, for example
+`database_url should use CONSTANT_CASE: DATABASE_URL`.
```
[the remark this answers is not in the document]
Comment (Nitjsefnie) [reply docs/lint/rules/deterministic/constant-case.md:12]: Agreed, and this one was a real doc inaccuracy — confirmed against the binary:

```
$ printf 'apiToken=x\n' > .env && vaar lint --only=constant-case
warn constant-case .env:1 apiToken should use CONSTANT_CASE: APITOKEN
```

`APITOKEN` isn't meaningfully CONSTANT_CASE, and the page's only example (`database_url` → `DATABASE_URL`) hid that because it already had its underscore. Fixed in b254a0a — the docs now state the suggestion uppercases ASCII lowercase letters and inserts nothing, call out `apiToken` → `APITOKEN` explicitly, and note the suggestion is a starting point where a key needs new underscores.

Left the rule's behaviour alone: inferring word boundaries in `apiToken` is a guess, and this rule is in the deterministic set.

**Comment by Nitjsefnie** [comment]
Apologies — I broke this PR's CI and have fixed it in 865fb0d.

**What happened:** when #30 merged it added `Description()` to the `lint.Rule` interface. This branch adds a *new* rule written before that, so the moment #30 landed, the merge result stopped compiling:

```
internal/lint/rules/deterministic/constant_case.go:19:43: cannot use constantCaseRule{} ... 
  does not implement lint.Rule (missing method Description)
```

That's the #30↔#33 collision we'd both flagged, just in a sharper form than a rebase — and my mistake is that I pushed the test/docs commit before it without catching this. The branch **on its own** still compiled, so testing it in isolation looked green; only the merge-with-main result breaks, which is what CI builds. I've since started rebasing onto `main` before verifying anything here.

**The fix:** rebased onto current `main` and gave the rule its description —

```go
func (constantCaseRule) Description() string { return "warns about portable keys that are not CONSTANT_CASE" }
```

Verified on the rebased tree before pushing: `go build ./...` and `go vet ./...` clean, `gofmt -l` empty, and the Hygiene smoke step reproduced verbatim (`rsync` to a temp dir → `go run ./cmd/vaar lint`) exits 0. It also now shows up where #30 put it:

```
NAME                 DESCRIPTION
constant-case        warns about portable keys that are not CONSTANT_CASE
```

CI is green again. The earlier review fixes (the `invalid-key-name` boundary assertion and the `APITOKEN` docs wording) are unchanged and rode along in the rebase.

**Review by TFM-HITESH — APPROVED** [review]
lgtm
